name: "get-values"
version: "0.1.1"
usage: "A helm plugin to allow for easy application of a charts default values when using helm dependencies"
description: |-
  A helm plugin to allow for easy application of a charts default values when using helm dependencies.
ignoreFlags: false
useTunnel: true
command: "get-values"